version: "3.8"

services:
  app:
    image: chainference-frontend
    build:
      # We add the parent folder to build context because the frontend app depends on it (such as
      # for the anchor program IDL).
      context: ../
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=3222
    ports:
      - "80:3222"
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  caddy_data:
  caddy_config:
