FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl git build-essential unzip

RUN curl -fsSL https://bun.sh/install | bash && \
    echo 'export PATH="/root/.bun/bin:$PATH"' >> /root/.bashrc

WORKDIR /app

COPY . /app

# This dockerfile is meant to be built in the context of the parent folder, so now we get back in
# the current folder.
WORKDIR /app/frontend

RUN /root/.bun/bin/bun install

CMD ["/root/.bun/bin/bun", "run", "prod"]
