FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl git build-essential unzip

RUN curl -fsSL https://bun.sh/install | bash && \
    export PATH="$HOME/.bun/bin:$PATH"

WORKDIR /app
COPY . .

RUN ~/.bun/bin/bun install

CMD ["~/.bun/bin/bun", "run", "prod"]
