#cloud-config

# cloud-init file used to initialize VPS.
# See documentation: https://cloudinit.readthedocs.io/en/latest/reference/modules.html
#
# You can paste this file in the host's web UI when creating a VPS.
#
# Execution logs are available at `/var/log/cloud-init-output.log`, with
# additional logging available in `/var/log/cloud-init.log`.
#
# Check that execution was successful by running:
# `grep "setup script ran successfully" /var/log/cloud-init-output.log`.

ssh_keys:
  ed25519_private: |
    paste private SSH key here!

timezone: UTC
ssh_pwauth: false # Disable SSH password auth.
disable_root: true # Disable root login over SSH.

users:
  - name: bernardo
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBesw1jrqTa2CepHsk35RX1wZeT5CCM1hBgbS8KDLS9D bfar97@gmail.com"
  - name: marcos
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGJ2vrIhoGkV+8kath2C3utUJ8zymmascDMWpLQs1Yrr email@marcospereira.me"
  - name: github
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDR7JRuR3FgsI2RRqtb5mS00jO/emFGS0cyM3M1n6Up2 github"

write_files:
  # Harden network security.
  - path: /etc/sysctl.d/99-cloud-hardening.conf
    content: |
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
    owner: root:root
    permissions: "0644"

  # Write commands into a bash script so that we can run them with bash explicitly ("runcmd"
  # commands may use a different shell).
  # Written to /run/ instead of /tmp/ as per
  # https://cloudinit.readthedocs.io/en/latest/reference/modules.html#runcmd
  - path: /run/vps-setup.sh
    permissions: "0700" # Executable
    content: |
      #!/bin/bash

      set -euxo pipefail

      printf "\n\n ========> Update packages \n\n"
      apt update -y
      # Same as apt upgrade but will add & remove packages as appropriate.
      apt dist-upgrade -y

      printf "\n\n ========> unattended-upgrades \n\n"

      apt install -y unattended-upgrades

      cat <<EOF > /etc/apt/apt.conf.d/20auto-upgrades
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      EOF

      cat <<EOF > /etc/apt/apt.conf.d/50unattended-upgrades
      Unattended-Upgrade::Allowed-Origins {
        "\${distro_id}:\${distro_codename}-security";
        "\${distro_id}:\${distro_codename}-updates";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
      EOF

      systemctl enable --now unattended-upgrades

      printf "\n\n ========> Fail2ban \n\n"
      apt install -y fail2ban
      systemctl enable fail2ban
      systemctl start fail2ban

      printf "\n\n ========> Firewall \n\n"
      ufw allow OpenSSH
      ufw --force enable

      printf "\n\n ========> Docker \n\n"
      apt install -y docker.io docker-compose
      systemctl enable --now docker

      printf "\n\n ========> setup script ran successfully \n\n"

runcmd:
  - "bash /run/vps-setup.sh"
  - "rm /run/vps-setup.sh"
