name: Deploy to VPS
on:
  push:
    branches:
      - main
env:
  VPS_HOST: "5.161.78.151"
  VPS_USER: "github"
  PROJECT_PATH: "/srv/chainference"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          temp_key=$(mktemp)
          echo "${{ secrets.SSH_KEY }}" > "$temp_key"
          chmod 600 "$temp_key"

          ssh -i "$temp_key" -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} << EOF
          set -euxo pipefail

          # Ensure GitHub's host key is in known_hosts to prevent host verification errors
          sudo -u github ssh-keyscan github.com >> /home/github/.ssh/known_hosts

          # Check if the project folder is a valid git repo
          if [ ! -d "${PROJECT_PATH}/.git" ]; then
            echo "Project directory is missing or not a git repository. Performing initial setup..."
            sudo rm -rf "${PROJECT_PATH}"
            sudo mkdir -p "${PROJECT_PATH}"
            sudo chown -R ${VPS_USER}:${VPS_USER} "${PROJECT_PATH}"
            sudo -u github git clone --depth=1 git@github.com:marcospgp/chainference.git "${PROJECT_PATH}"
            cd "${PROJECT_PATH}"
          else
            echo "Project directory exists and is a git repository. Updating..."
            cd "${PROJECT_PATH}"
            sudo -u github git fetch --depth=1
            sudo -u github git reset --hard origin/main
          fi
          cd frontend
          sudo docker compose down
          sudo docker compose up -d --build
          EOF

          rm "$temp_key"
